openapi: 3.0.0
info:
  title: CRM
  description:
  version: '1.0'
  x-ibm-application-icon: <svg id="Layer_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 54 52.18"><text transform="translate(0 40.18)" style="fill:#2e3192; font-family:MyriadPro-Regular, &apos;Myriad Pro&apos;; font-size:48px;"><tspan x="0" y="0">L3</tspan></text></svg>
servers:
  - url: https://wxo-l3-services.1d13bpwyy9q7.us-east.codeengine.appdomain.cloud
paths:
  /query?q=select+Id,AccountId,Name,Email,Recent_Change__c,Child_Age__c,Child_Covered__c,Child_Name__c+from+contact+where+AccountId='001Hs00002ubq6YIAQ':
    get:
      tags:
        - Customers
      summary: Get Customers with recent life events
      description: Get Customers with recent life events
      operationId: get_customers_with_recent_life_events
      responses:
        '200':
          description: Customer life events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - HTTPBasic: []
components:
  schemas:
    Customer:
      properties:
        name:
          type: string
          title: Name
        age:
          type: integer
          title: Age
        id:
          type: string
          title: Id
        accountId:
          type: string
          title: Accountid
        email:
          type: string
          title: Email
        recent_change:
          type: string
          title: Recent Change
        current_products:
          items:
            type: string
          type: array
          title: Current Products
      type: object
      required:
        - name
        - age
        - id
        - accountId
        - email
        - recent_change
        - current_products
      title: Customer
    Customers:
      properties:
        totalSize:
          type: integer
          title: Totalsize
          x-ibm-show: false
        records:
          items:
            $ref: '#/components/schemas/Customer'
          type: array
          title: Records
      type: object
      required:
        - totalSize
        - records
      title: Customers
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic